name: Greet Contributor

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome-issue:
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issues' }}
    steps:
      - uses: actions/github-script@v6
        if: ${{ github.event.sender.login != github.repository_owner }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Hello @${{ github.actor }}, Thank you for raising the issue.

                Maintainer will soon investigate into the issue and get back to you as soon as possible.`
            })
  welcome-pull_request:
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' }}
    steps:
      - uses: actions/github-script@v6
        if: ${{ github.event.sender.login != github.repository_owner }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Hello @${{ github.actor }}, Thank you for raising a pull request.

                Please make sure you have filled the PR template properly and followed our contributing guidelines.`
            })

