name: Greet Contributor

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        if: ${{ github.event.sender.login != github.repository_owner }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            ### Hello @${{ github.actor }}, Thank you for raising the issue.

            Maintainer will soon investigate into the issue and get back to you as soon as possible.

          pr-message: |
            ### Hello @${{ github.actor }}, Thank you for raising a pull request.

            Please make sure you have filled the PR template properly and followed our contributing guidelines.
